#!/usr/bin/python3


from cliplauncher import ClipLauncher, SooperLooperTrack


Track = SooperLooperTrack


ClipLauncher([

    Track(u'Deck A', [
        '/home/epimetheus/hear/samples/favorites/drums/140bpm-vec3-breakbeat-011.wav',
        '/home/epimetheus/hear/samples/favorites/drums/140bpm-vec3-breakbeat-011.wav',
        '/home/epimetheus/hear/samples/favorites/drums/140bpm-vec3-breakbeat-011.wav',
        '/home/epimetheus/hear/samples/favorites/drums/140bpm-vec3-breakbeat-011.wav',
        ]),

    Track(u'Deck B', [
        '/home/epimetheus/hear/samples/favorites/drums/140bpm-vec3-breakbeat-011.wav',
        '/home/epimetheus/hear/samples/favorites/drums/140bpm-vec3-breakbeat-011.wav',
        '/home/epimetheus/hear/samples/favorites/drums/140bpm-vec3-breakbeat-011.wav',
        '/home/epimetheus/hear/samples/favorites/drums/140bpm-vec3-breakbeat-011.wav',
        ]),

]).start()

